[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = '''
    default-src 'self';
    script-src 'self';
    object-src 'none';
    style-src 'self';
    img-src 'self';
    media-src 'none';
    frame-src 'none';
    font-src 'self';
    connect-src 'none'
    '''
    X-Content-Security-Policy = '''
    default-src 'self';
    script-src 'self';
    object-src 'none';
    style-src 'self';
    img-src 'self';
    media-src 'none';
    frame-src 'none';
    font-src 'self';
    connect-src 'none'
    '''
    X-WebKit-CSP = '''
    default-src 'self';
    script-src 'self';
    object-src 'none';
    style-src 'self';
    img-src 'self';
    media-src 'none';
    frame-src 'none';
    font-src 'self';
    connect-src 'none'
    '''