[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = '''
    default-src 'self';
    prefetch-src 'data:false;base64,aW1wb3J0IFJlYWN0IGZyb20gJ3JlYWN0JwppbXBvcnQgeyByZW5kZXIgfSBmcm9tICdyZWFjdC1kb20nCmltcG9ydCAnLi90YWlsd2luZC5jc3MnCmltcG9ydCBBcHAgZnJvbSAnLi9BcHAnCmltcG9ydCB7VGhlbWVDb250ZXh0UHJvdmlkZXJ9IGZyb20gJy4vdGhlbWVDb250ZXh0JwoKY29uc3QgdGltZSA9IChuZXcgRGF0ZSgpKS50b0xvY2FsZVN0cmluZygnZW4tVVMnLCB7CiAgaG91cjogJ251bWVyaWMnLAogIG1pbnV0ZTogJ251bWVyaWMnLAogIGhvdXIxMjogdHJ1ZQp9KQoKcmVuZGVyKAogIDxUaGVtZUNvbnRleHRQcm92aWRlcj4KICAgICAgPEFwcCAvPgogICAgPC9UaGVtZUNvbnRleHRQcm92aWRlcj4sCiAgZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoJ3Jvb3QnKQopCg==';
    script-src 'self';
    object-src 'none';
    style-src 'self';
    img-src 'self';
    media-src 'none';
    frame-src 'none';
    font-src 'self';
    connect-src 'none';
    frame-ancestors 'none';
    '''
    X-Content-Security-Policy = '''
    default-src 'self';
    prefetch-src 'data:false;base64,aW1wb3J0IFJlYWN0IGZyb20gJ3JlYWN0JwppbXBvcnQgeyByZW5kZXIgfSBmcm9tICdyZWFjdC1kb20nCmltcG9ydCAnLi90YWlsd2luZC5jc3MnCmltcG9ydCBBcHAgZnJvbSAnLi9BcHAnCmltcG9ydCB7VGhlbWVDb250ZXh0UHJvdmlkZXJ9IGZyb20gJy4vdGhlbWVDb250ZXh0JwoKY29uc3QgdGltZSA9IChuZXcgRGF0ZSgpKS50b0xvY2FsZVN0cmluZygnZW4tVVMnLCB7CiAgaG91cjogJ251bWVyaWMnLAogIG1pbnV0ZTogJ251bWVyaWMnLAogIGhvdXIxMjogdHJ1ZQp9KQoKcmVuZGVyKAogIDxUaGVtZUNvbnRleHRQcm92aWRlcj4KICAgICAgPEFwcCAvPgogICAgPC9UaGVtZUNvbnRleHRQcm92aWRlcj4sCiAgZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoJ3Jvb3QnKQopCg==';
    script-src 'self';
    object-src 'none';
    style-src 'self';
    img-src 'self';
    media-src 'none';
    frame-src 'none';
    font-src 'self';
    connect-src 'none';
    frame-ancestors 'none';
    '''
    X-WebKit-CSP = '''
    default-src 'self';
    prefetch-src 'data:false;base64,aW1wb3J0IFJlYWN0IGZyb20gJ3JlYWN0JwppbXBvcnQgeyByZW5kZXIgfSBmcm9tICdyZWFjdC1kb20nCmltcG9ydCAnLi90YWlsd2luZC5jc3MnCmltcG9ydCBBcHAgZnJvbSAnLi9BcHAnCmltcG9ydCB7VGhlbWVDb250ZXh0UHJvdmlkZXJ9IGZyb20gJy4vdGhlbWVDb250ZXh0JwoKY29uc3QgdGltZSA9IChuZXcgRGF0ZSgpKS50b0xvY2FsZVN0cmluZygnZW4tVVMnLCB7CiAgaG91cjogJ251bWVyaWMnLAogIG1pbnV0ZTogJ251bWVyaWMnLAogIGhvdXIxMjogdHJ1ZQp9KQoKcmVuZGVyKAogIDxUaGVtZUNvbnRleHRQcm92aWRlcj4KICAgICAgPEFwcCAvPgogICAgPC9UaGVtZUNvbnRleHRQcm92aWRlcj4sCiAgZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoJ3Jvb3QnKQopCg==';
    script-src 'self';
    object-src 'none';
    style-src 'self';
    img-src 'self';
    media-src 'none';
    frame-src 'none';
    font-src 'self';
    connect-src 'none';
    frame-ancestors 'none';
    '''
    X-Frame-Options = 'DENY'
    X-Content-Type-Options = 'nosniff'

[[headers]]
  for = "/_assets/*"
  [headers.values]
    cache-control = '''
    public,
    max-age: 2592000,
    must-revalidate'''